[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
private_credit = "69qmzHFdDMP8hGFNcJcKpduGbdjEnAhdrvLrLaydvvRc"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
