import { ChevronDown, HelpCircle, MessageCircleQuestion } from "lucide-react";
import type { SiteView } from "../../config/navigation";
import { ContentHero, PageCta } from "./ContentPageShell";

const faqGroups = [
  {
    title: "Access and evidence",
    questions: [
      {
        question: "Which wallets and networks are supported?",
        answer: "Sepolia is read for real: the ENS registry, the PublicResolver, and a direct text(node, key) call for the payout record. On the Solana side the app does not ask you to connect a wallet at all -- settlement is signed by demo keypairs the backend holds, so a reviewer can see the protocol work without installing an extension or winning a faucet lottery. The transactions are real and open in an explorer; the custody is not the production design, and the settlement panel says so.",
      },
      {
        question: "Do I need an ENS name?",
        answer: "The flow uses an ENS name as its portable identity anchor. ENS records are public. A production system could support other identity methods, but this prototype has not implemented them.",
      },
      {
        question: "Where does portfolio data come from?",
        answer: "One source. The applicant supplies a Solana address and the backend reads it from Solana mainnet RPC, prices the holdings through Jupiter, and returns a snapshot. Both are keyless—no vendor account, no API key. Only nine allowlisted mints count toward the numbers: wSOL, USDC, USDT, JitoSOL, mSOL, bSOL, JupSOL, WBTC, and WETH. That allowlist, and the denylist used for the restricted-exposure claim, are committed in the repository. Note the deliberate split: balances are read from mainnet while settlement targets Solana devnet.",
      },
      {
        question: "How do I know this isn’t a hard-coded demo?",
        answer: "Paste any Solana mainnet address, including your own, and the numbers change—there is no fixture snapshot to fall back on. Every passport response carries a provenance strip naming each RPC endpoint that was called and the measured latency of each call, alongside the allowlist and denylist that were applied. Both lists are in the repository, so you can check that what the strip claims to have used is what the code actually uses.",
      },
      {
        question: "What happens when a source is missing or unavailable?",
        answer: "The result should remain unavailable or incomplete—not be silently converted into a pass, fail, or zero balance. An account age the bounded signature scan cannot establish is reported as “cannot establish” rather than guessed, and a mint Jupiter returns no price for is flagged instead of valued at zero.",
      },
    ],
  },
  {
    title: "Proofs and decisions",
    questions: [
      {
        question: "What does a passing proof establish?",
        answer: "Only that the supplied witness satisfied the encoded claims for a specific policy and snapshot. The four claims are: allowlisted assets meet the policy minimum; enough of the portfolio sits in stablecoins and liquid staking tokens; the account is at least as old as the policy requires; and no denylisted mint is held. It does not guarantee repayment, future solvency, data-provider correctness, legal eligibility, or funding.",
      },
      {
        question: "Is this actually zero-knowledge yet?",
        answer: "Yes. The receipt is a BN254 Groth16 proof of a 2 980-constraint circuit, generated by a Web Worker in the applicant’s browser — the portfolio values are arguments to that worker and are never in any request body — and the backend verifies the pairing equation with snarkjs against a committed verifying key. Two honest caveats. First, the trusted setup is a development ceremony: two phase-2 contributions, a published transcript, one machine, one person, so whoever ran it could forge proofs. Second, the proof shows the policy holds over the snapshot the applicant’s own client read from Solana RPC; it proves honest computation, not that the snapshot is the right wallet. Everything around the receipt is enforced too: the passport commitment is published before the policy challenge is issued, the backend recomputes the policy hash instead of trusting the client, receipts expire, and a nullifier makes a second presentation fail.",
      },
      {
        question: "Can one proof be reused with several lenders?",
        answer: "Only when those lenders accept the same policy, source coverage, public inputs, verifier, and validity window. Safer implementations bind proofs to a versioned challenge so reuse cannot change their meaning.",
      },
      {
        question: "Why do proofs expire?",
        answer: "Portfolio conditions change. Expiry limits how long a point-in-time claim can be treated as current. The policy challenge carries the validity window and the backend rejects a receipt presented after it.",
      },
      {
        question: "What happens if proof generation or verification fails?",
        answer: "A technical failure is an unknown result, not a failed eligibility claim. The product should show whether the cause is expiry, unsupported data, user rejection, malformed inputs, or verifier failure before offering a retry.",
      },
      {
        question: "Why might an eligible applicant still be rejected?",
        answer: "Capital providers remain responsible for liquidity, pricing, jurisdiction, counterparty, concentration, fraud, and repayment risk. Passing the configured claims is necessary only when the provider says it is—not sufficient for approval.",
      },
    ],
  },
  {
    title: "Privacy, cost, and settlement",
    questions: [
      {
        question: "What stays private from the capital provider?",
        answer: "The total portfolio value, the per-token balances behind it, the measured collateral-quality share, and the measured account age. The provider sees the public request terms, the passport commitment, the four claim outcomes, the receipt metadata, and the provenance strip—which names the Solana address the snapshot was read from. That address is not hidden.",
      },
      {
        question: "Does zero knowledge make the whole interaction anonymous?",
        answer: "No. The backend we operate proxies the portfolio read, so it sees the address, the values read on your behalf, and your request timing and IP. Beyond that, hosting, RPC, and pricing providers observe timestamps, queries, and public identifiers; ENS and transaction records are public; and counterparties can correlate repeated behavior.",
      },
      {
        question: "What does it cost?",
        answer: "The prototype charges nothing and moves no funds. A production flow could include proof-generation infrastructure, provider, gas, origination, financing, and settlement costs; none are finalized here.",
      },
      {
        question: "Is the product non-custodial?",
        answer: "The current prototype cannot custody anything because it has no live settlement. The target experience is non-custodial, but that claim must be reassessed against the deployed contracts, upgrade controls, approvals, and recovery mechanisms.",
      },
      {
        question: "Are offers and loan settlement live?",
        answer: "Yes, end to end. Requests, policy challenges, receipts, offers, acceptance and the loan lifecycle are real records created by real HTTP calls against the marketplace backend, which the two parties reach as separate clients. The proof is a real Groth16 proof produced in the applicant browser. The one-time payout addresses are really derived from a key read out of ENS on Sepolia. And settlement is a real Anchor program on a Solana test cluster that verifies the proof itself with the BN254 pairing syscalls, recomputes the policy hash from its own stored account, creates a nullifier account that makes a second presentation impossible, and moves an SPL escrow to the payout address. Nothing waits on a timer pretending to work. What is a demonstration rather than a product: the trusted setup, the minted test token, and the custodial demo keypairs.",
      },
    ],
  },
];

export function FaqPage({ onNavigate }: { onNavigate: (view: SiteView) => void }) {
  return (
    <div className="content-page">
      <ContentHero
        eyebrow="Frequently asked questions"
        title="Clear answers before you connect."
        lead="The short version: this is an experimental prototype spanning two chains. Portfolio balances are read live from Solana mainnet, ENS is read live on Sepolia, the marketplace runs against a real backend, and settlement runs against a real Anchor program on a Solana test cluster. What it is not: audited, ceremonially trustworthy, or holding anyone funds. It demonstrates a privacy boundary and a complete decision flow, not production lending."
        aside={
          <div className="faq-hero-mark">
            <HelpCircle size={30} />
            <strong>16 answers</strong>
            <span>Across access, proofs, privacy, costs, and settlement.</span>
          </div>
        }
      />

      <div className="faq-groups">
        {faqGroups.map((group) => (
          <section className="faq-group" key={group.title}>
            <div className="faq-group__heading">
              <MessageCircleQuestion size={20} />
              <h2>{group.title}</h2>
            </div>
            <div className="faq-list">
              {group.questions.map((item) => (
                <details key={item.question}>
                  <summary>{item.question}<ChevronDown size={18} /></summary>
                  <p>{item.answer}</p>
                </details>
              ))}
            </div>
          </section>
        ))}
      </div>

      <PageCta
        eyebrow="Still exploring?"
        title="See the answers in context."
        body="The app shows what the borrower publishes and what the lender actually receives."
        primary={{ view: "how-it-works", label: "See how it works" }}
        secondary={{ view: "security", label: "Read security & trust" }}
        onNavigate={onNavigate}
      />
    </div>
  );
}
